/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AccountList: typeof import('./components/AccountList.vue')['default']
    Changelog: typeof import('./components/Changelog.vue')['default']
    CreateWallet: typeof import('./components/svgIcon/CreateWallet.vue')['default']
    EyeClose: typeof import('./components/svgIcon/EyeClose.vue')['default']
    EyeOpen: typeof import('./components/svgIcon/EyeOpen.vue')['default']
    Fast: typeof import('./components/svgIcon/Fast.vue')['default']
    HomeCenter: typeof import('./components/HomeCenter.vue')['default']
    IconBack: typeof import('./components/svgIcon/IconBack.vue')['default']
    Import: typeof import('./components/svgIcon/Import.vue')['default']
    ImportWallet: typeof import('./components/svgIcon/ImportWallet.vue')['default']
    Logo: typeof import('./components/svgIcon/logo.vue')['default']
    Medium: typeof import('./components/svgIcon/Medium.vue')['default']
    ReceiveBtc: typeof import('./components/ReceiveBtc.vue')['default']
    ReceiveTaproot: typeof import('./components/ReceiveTaproot.vue')['default']
    ReceiveTaprootHistory: typeof import('./components/ReceiveTaprootHistory.vue')['default']
    Refresh: typeof import('./components/svgIcon/Refresh.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectGas: typeof import('./components/SelectGas.vue')['default']
    SendBtc: typeof import('./components/SendBtc.vue')['default']
    SendTaproot: typeof import('./components/SendTaproot.vue')['default']
    Slow: typeof import('./components/svgIcon/Slow.vue')['default']
  }
}
