name: release
'on':
  push:
    branches:
      - master

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: 'bash'

jobs:
  draft_release:
    permissions:
      contents: write # Allows this job to create releases

    strategy:
      fail-fast: true
      matrix:
        # os: [macos-latest, ubuntu-latest, windows-latest]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          # cache: 'pnpm'
      - uses: pnpm/action-setup@v2
        with:
            version: latest
      
      - run: pnpm i
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

      - name: Get Package Version
        id: get-version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - run: pnpm run build
      - run: zip -r ${{ env.version }}.zip dist/build

      - name: GH Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ env.version }}
          name: ${{ env.version }}
          draft: true
          files: ${{ env.version }}.zip
